"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import bundledCatalog from "./data/key-catalog.json";
import {filterKeys,formatCatalogTime,keyPriceRows,keyTaskEvidence,keyUsesLabel,mergeKeyCatalogWithBundled,normalizeKeyText} from "./key-wiki-utils.mjs";
import {arrayOrEmpty,parseStoredRecord} from "./render-safety.mjs";
import {startupRequests} from "./startup-data.mjs";

type KeyWikiProps={onOpenTask:(taskId:string,trader:string)=>void;};
const keyCategory=(key:any)=>/keycard|card key|キーカード/i.test(`${key.name} ${key.nameEn}`)?"カードキー":/marked|マーク/i.test(`${key.name} ${key.nameEn}`)?"マークドキー":arrayOrEmpty(key.mapUses).some((map:any)=>map.kind==="access")?"入場用キー":"通常鍵";
const mapEvidenceLabel=(kind:string)=>kind==="door"?"マップのLock情報":kind==="access"?"マップのアクセスキー":kind==="task"?"タスク目標の対象マップ":"既存Wikiの使用場所情報";
const taskRequirementLabel=(task:any)=>task?.alternative?(task?.requirements?.some((entry:any)=>!entry.alternative)?"必須・代替候補":"代替候補（同じグループのいずれか）"):"必須";
const rub=(value:number)=>`${new Intl.NumberFormat("ja-JP").format(value)}₽`;

export default function KeyWiki({onOpenTask}:KeyWikiProps){
  const saved=useMemo(()=>typeof window==="undefined"?{}:parseStoredRecord(sessionStorage.getItem("tarkov-key-wiki-view")),[]),initial:any=bundledCatalog;
  const [catalog,setCatalog]=useState<any>(initial),[query,setQuery]=useState(String(saved.query||"")),[mapFilter,setMapFilter]=useState(String(saved.mapFilter||"all")),[usage,setUsage]=useState<"all"|"task"|"other">((["all","task","other"].includes(saved.usage)?saved.usage:"all") as any),[selectedId,setSelectedId]=useState(String((typeof history!=="undefined"&&history.state?.keySelected)||saved.selectedId||initial.keys?.[0]?.id||"")),[loading,setLoading]=useState(false),[status,setStatus]=useState("同梱データを表示中"),[refreshError,setRefreshError]=useState("");
  const applyCatalog=useCallback((value:any,label:string)=>{if(!Array.isArray(value?.keys)||!value.keys.length)return false;setCatalog(mergeKeyCatalogWithBundled(value,initial));setStatus(label);setRefreshError("");return true},[initial]);
  const refresh=useCallback(async()=>{const api=(window as any).stashAI;if(!api?.refreshKeys)return;setLoading(true);try{const value=await startupRequests.refreshKeys(api);if(!applyCatalog(value,"最新の鍵データに更新しました")){setRefreshError(String(value?.error||"鍵データを更新できませんでした"));setStatus("保存済みデータを表示中")}}catch{setRefreshError("鍵データを更新できませんでした");setStatus("保存済みデータを表示中")}finally{setLoading(false)}},[applyCatalog]);
  useEffect(()=>{let cancelled=false;const api=(window as any).stashAI;if(!api?.keys)return;setLoading(true);startupRequests.savedKeys(api).then((value:any)=>{if(!cancelled)applyCatalog(value,`${value?.source||"保存済み"}データを表示中`)}).catch(()=>{}).finally(()=>{if(!cancelled)setLoading(false)});if(api.refreshKeys)startupRequests.refreshKeys(api).then((value:any)=>{if(cancelled)return;if(!applyCatalog(value,"最新の鍵データに更新しました")&&value?.error){setRefreshError(String(value.error));setStatus("保存済みデータを表示中")}}).catch(()=>{if(!cancelled)setRefreshError("鍵データを更新できませんでした")});return()=>{cancelled=true}},[applyCatalog]);
  useEffect(()=>{try{sessionStorage.setItem("tarkov-key-wiki-view",JSON.stringify({query:query.slice(0,100),mapFilter,usage,selectedId}))}catch{}},[query,mapFilter,usage,selectedId]);

  const keys=arrayOrEmpty(catalog?.keys),mapOptions=useMemo(()=>[...new Map(keys.flatMap((key:any)=>arrayOrEmpty(key?.mapUses)).map((map:any)=>[map?.id,{id:map?.id,name:map?.name,nameEn:map?.nameEn}])).values()].filter((map:any)=>map.id).sort((a:any,b:any)=>String(a.name).localeCompare(String(b.name),"ja")),[keys]),visible=useMemo(()=>filterKeys(keys,{query,map:mapFilter,usage}),[keys,query,mapFilter,usage]),selected=keys.find((key:any)=>key?.id===selectedId)||visible[0]||null,taskKeyCount=keys.filter((key:any)=>arrayOrEmpty(key?.tasks).length).length,mapCount=new Set(keys.flatMap((key:any)=>arrayOrEmpty(key?.mapUses).map((map:any)=>map?.id).filter(Boolean))).size;
  useEffect(()=>{if(visible.length&&(!selectedId||!visible.some((key:any)=>key.id===selectedId)))setSelectedId(visible[0].id)},[visible,selectedId]);
  const clearFilters=()=>{setQuery("");setMapFilter("all");setUsage("all")};
  const lockLocation=selected?(selected.lockLocation||selected.lockLocationEn||""):"",behindLock=selected?(selected.behindLock||selected.behindLockEn||""):"",mapEvidence=selected?arrayOrEmpty(selected.mapUses):[],locationMaps=[...new Map<string,string>(mapEvidence.map((map:any):[unknown,unknown]=>[map?.id,map?.name||map?.nameEn]).filter((entry):entry is [string,string]=>entry.every(value=>typeof value==="string"&&value.length>0))).values()],lockLocationMaps=[...new Map<string,string>(mapEvidence.filter((map:any)=>map?.kind==="door"||map?.kind==="wiki").map((map:any):[unknown,unknown]=>[map?.id,map?.name||map?.nameEn]).filter((entry):entry is [string,string]=>entry.every(value=>typeof value==="string"&&value.length>0))).values()],taskEvidence=selected?keyTaskEvidence(selected):null,prices=selected?keyPriceRows(selected):[],usesLabel=selected?keyUsesLabel(selected.uses):"",priceTime=selected?.priceStatus==="available"?formatCatalogTime(catalog?.updatedAt):"確認できません",canRefresh=typeof window!=="undefined"&&Boolean((window as any).stashAI?.refreshKeys),hasPartialData=selected&&(selected.taskRelationsStatus!=="available"||selected.mapUsesStatus!=="available"||selected.priceStatus!=="available");

  const renderTask=(task:any,kind:"required"|"other")=><button type="button" key={`${kind}:${task?.id}`} onClick={()=>onOpenTask(task?.id,task?.trader)}><b>LV.{task?.level}</b><span><strong>{task?.name}</strong>{normalizeKeyText(task?.name)!==normalizeKeyText(task?.nameEn)&&<small>{task?.nameEn}</small>}<em>{task?.trader}{task?.map?.name?` · 対象マップ ${task.map.name}`:" · 対象マップ未登録"}</em><mark>{kind==="required"?taskRequirementLabel(task):"その他のAPI関連"}{task?.objectiveCount>1?` · ${task.objectiveCount}目標で使用`:""}</mark></span><i>タスク情報へ ›</i></button>;

  return <section className="keyWiki"><header className="keyWikiHero"><div><small>KEY INTELLIGENCE</small><h2>鍵Wiki</h2><p>レイドで拾った鍵の用途と相場を、断定や推奨をせず確認できます。</p></div><div className="keyWikiStats"><span><b>{keys.length}</b>収録鍵</span><span><b>{taskKeyCount}</b>鍵タスク登録</span><span><b>{mapCount}</b>関連マップ</span></div></header>
    <section className="keyWikiToolbar"><label className="keySearch"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="鍵名・タスク名・マップ名で検索…" autoComplete="off"/>{query&&<button type="button" onClick={()=>setQuery("")} aria-label="検索を消去">×</button>}</label><label><span>使用マップ</span><select value={mapFilter} onChange={event=>setMapFilter(event.target.value)}><option value="all">すべてのマップ</option>{mapOptions.map((map:any)=><option key={map.id} value={map.id}>{map.name}</option>)}</select></label><div className="keyUsageSwitch" role="group" aria-label="鍵タスク登録で絞り込み"><button className={usage==="all"?"active":""} onClick={()=>setUsage("all")}>すべて</button><button className={usage==="task"?"active":""} onClick={()=>setUsage("task")}>鍵タスク登録あり</button><button className={usage==="other"?"active":""} onClick={()=>setUsage("other")}>鍵タスク未登録</button></div></section>
    <div className="keyWikiStatus"><span>{loading?"最新データを確認中…":status}{refreshError&&<> · <strong>更新に失敗しました</strong></>}</span><b>{visible.length}件</b></div>
    <div className="keyWikiLayout"><section className="keyResults" aria-label="鍵の検索結果">{visible.length?visible.map((key:any,index:number)=>{const active=selected?.id===key.id,keyMaps=arrayOrEmpty(key.mapUses),keyTasks=arrayOrEmpty(key.tasks),known=key.taskRelationsStatus==="available";return <button type="button" className={active?"active":""} key={key.id} onClick={()=>setSelectedId(key.id)}><img src={key.image} alt="" loading={index===0?"eager":"lazy"} decoding="async"/><span><strong>{key.name}</strong>{normalizeKeyText(key.name)!==normalizeKeyText(key.nameEn)&&<small>{key.nameEn}</small>}<i>{keyMaps.slice(0,2).map((map:any)=>map?.name).filter(Boolean).join(" · ")||"関連マップ未登録"}</i></span><em className={keyTasks.length?"taskUsed":""}>{keyTasks.length?`KEY TASK ${keyTasks.length}`:known?"登録なし":"未確認"}</em></button>}):<div className="keyEmpty"><b>該当する鍵がありません</b><span>検索語または絞り込み条件を変更してください。</span><button type="button" onClick={clearFilters}>条件をリセット</button></div>}</section>
      <aside className="keyDetail">{selected?<><header><div className="keyDetailImage"><img src={selected.inspectImage||selected.image} onError={event=>{event.currentTarget.src=selected.image}} alt={`${selected.name}の画像`} loading="eager" decoding="async"/></div><div><small>SELECTED KEY</small><h2>{selected.name}</h2>{normalizeKeyText(selected.name)!==normalizeKeyText(selected.nameEn)&&<p>{selected.nameEn}</p>}<div className="keyDetailBadges"><span>{keyCategory(selected)}</span><span>{usesLabel}</span><span className={taskEvidence?.required.length?"important":""}>{taskEvidence?.status==="available"?`鍵タスク ${taskEvidence.required.length}件`:"タスク関連未確認"}</span></div></div></header>
        <section className="keyJudgment"><header><small>DECISION MATERIALS</small><h3>判断材料</h3><p>保持・売却の推奨ではなく、APIと既存Wikiで確認できた材料です。</p></header>{hasPartialData&&<div className="keyPartialNotice"><span>一部の判断材料を取得できませんでした。取得済みの情報はそのまま表示しています。</span>{canRefresh&&<button type="button" onClick={refresh} disabled={loading}>再試行</button>}</div>}<div className="keyJudgmentGrid"><article><span>タスク用途</span><strong>{taskEvidence?.requiredLabel}</strong><small>{taskEvidence?.otherLabel}</small></article><article><span>使用マップ</span><strong>{locationMaps.length?`${locationMaps.length}件`:selected.mapUsesStatus==="available"?"API上の登録なし":"確認できません"}</strong><small>{locationMaps.slice(0,3).join(" · ")||"Lock・アクセス・タスク目標を別根拠で表示"}</small></article><article><span>使用回数</span><strong>{usesLabel.replace("最大使用回数：","")}</strong><small>ItemPropertiesKey.uses</small></article><article><span>参考相場</span>{prices.length?prices.map(price=><strong key={price.kind}>{price.label}：{rub(price.value)}</strong>):<strong>{selected.priceStatus==="available"?"API上の価格登録なし":"価格情報を取得できませんでした"}</strong>}<small>価格取得：{priceTime}</small></article></div>
          <details className="keyEvidenceDetails"><summary>根拠と関連タスクを表示</summary><div className="keyMapEvidence"><h4>使用マップの根拠</h4>{mapEvidence.length?<ul>{mapEvidence.map((map:any,index:number)=><li key={`${map?.id}:${map?.kind}:${index}`}><b>{map?.name||map?.nameEn||"マップ名未登録"}</b><span>{mapEvidenceLabel(map?.kind)}</span></li>)}</ul>:<p>{selected.mapUsesStatus==="available"?"API上の関連マップ登録はありません。":"関連マップを確認できませんでした。"}</p>}</div><div className="keyRelatedTasks"><h4>関連タスク</h4>{taskEvidence?.status!=="available"&&<div className="keyPartialNotice"><span>関連タスクを確認できませんでした。保存済みの候補がある場合だけ表示しています。</span>{canRefresh&&<button type="button" onClick={refresh} disabled={loading}>再試行</button>}</div>}{taskEvidence?.required.length?<section><h5>{taskEvidence.requiredLabel}</h5><div className="keyTaskRows">{taskEvidence.required.map((task:any)=>renderTask(task,"required"))}</div></section>:taskEvidence?.status==="available"&&<p>API上、鍵として必要なタスクは登録されていません。</p>}{taskEvidence?.other.length?<section><h5>{taskEvidence.otherLabel}</h5><div className="keyTaskRows">{taskEvidence.other.map((task:any)=>renderTask(task,"other"))}</div></section>:taskEvidence?.status==="available"&&<p>API上のその他タスク関連登録はありません。</p>}</div></details>
        </section>
        <section className="keyPurpose"><small>WHAT THIS KEY IS FOR</small><h3>用途</h3><p>{selected.description||selected.descriptionEn||"用途説明を取得できませんでした。Wikiで最新情報を確認してください。"}</p>{selected.description&&selected.descriptionEn&&normalizeKeyText(selected.description)!==normalizeKeyText(selected.descriptionEn)&&<details><summary>英語の原文を表示</summary><p>{selected.descriptionEn}</p></details>}</section>
        <section className="keyWikiIntel"><article className={selected.lockLocationSource==="wiki-section"?"verified":"unlisted"}><header><div><small>LOCK LOCATION</small><h3>鍵を使う場所</h3></div><span>{selected.lockLocationSource==="wiki-section"?"Wiki掲載":"補足情報"}</span></header>{lockLocationMaps.length>0&&<div className="keyLocationMaps" aria-label="Lock情報またはWikiで確認できた関連マップ"><small>Lock・Wikiで確認できたマップ</small><div>{lockLocationMaps.map((mapName:any)=><b key={mapName}>{mapName}</b>)}</div></div>}<p>{lockLocation||"英語Wikiに使用場所の記載がありません。"}</p>{selected.lockLocationEn&&normalizeKeyText(lockLocation)!==normalizeKeyText(selected.lockLocationEn)&&<details><summary>英語Wikiの原文を表示</summary><p>{selected.lockLocationEn}</p></details>}</article><article className={selected.behindLockSource==="wiki-section"?"verified":"unlisted"}><header><div><small>BEHIND THE LOCK</small><h3>開錠先で入手・利用できるもの</h3></div><span>{selected.behindLockSource==="wiki-section"?"Wiki掲載":"節の記載なし"}</span></header><p>{behindLock||"英語Wikiに具体的な入手物の記載がありません。"}</p>{selected.behindLockEn&&normalizeKeyText(behindLock)!==normalizeKeyText(selected.behindLockEn)&&<details><summary>英語Wikiの原文を表示</summary><p>{selected.behindLockEn}</p></details>}</article></section>
        <footer><span>DATA: tarkov.dev (regular) · Escape from Tarkov Wiki</span>{selected.wiki&&<a href={selected.wiki} target="_blank" rel="noreferrer">Wikiで詳細を確認 ↗</a>}</footer></>:<div className="keyDetailEmpty">左の一覧から鍵を選択してください。</div>}</aside></div>
  </section>;
}
