"use client";
import {useEffect,useMemo,useState} from "react";
import bundledCatalog from "./data/key-catalog.json";
import {filterKeys,mergeKeyCatalogWithBundled,normalizeKeyText} from "./key-wiki-utils.mjs";

type KeyWikiProps={onOpenTask:(taskId:string,trader:string)=>void;};
const keyCategory=(key:any)=>/keycard|card key|キーカード/i.test(`${key.name} ${key.nameEn}`)?"カードキー":/marked|マーク/i.test(`${key.name} ${key.nameEn}`)?"マークドキー":key.mapUses?.some((map:any)=>map.kind==="access")?"入場用キー":"通常鍵";
const keyDecision=(key:any)=>{if(key.tasks?.length)return{tone:"keep",title:"タスク用に保管",reason:`${key.tasks.length}件のタスクで必要です。使用前に対象タスクとマップを確認してください。`};if(key.mapUses?.length)return{tone:"use",title:"使用予定があれば保管",reason:`${key.mapUses.length}件の使用先が登録されています。出撃先と一致する場合だけ持ち込みます。`};return{tone:"unknown",title:"用途を特定できるまで判断保留",reason:"API上で使用場所を確認できていません。売却前にWikiの最新情報を確認してください。"}};

export default function KeyWiki({onOpenTask}:KeyWikiProps){
  const saved=useMemo(()=>{if(typeof window==="undefined")return{} as any;try{return JSON.parse(sessionStorage.getItem("tarkov-key-wiki-view")||"{}")}catch{return{} as any}},[]),initial:any=bundledCatalog;
  const [catalog,setCatalog]=useState<any>(initial),[query,setQuery]=useState(String(saved.query||"")),[mapFilter,setMapFilter]=useState(String(saved.mapFilter||"all")),[usage,setUsage]=useState<"all"|"task"|"other">((["all","task","other"].includes(saved.usage)?saved.usage:"all") as any),[selectedId,setSelectedId]=useState(String(saved.selectedId||initial.keys?.[0]?.id||"")),[loading,setLoading]=useState(false),[status,setStatus]=useState("同梱データを表示中");
  useEffect(()=>{let cancelled=false;const api=(window as any).stashAI;if(!api?.keys)return;setLoading(true);api.keys().then((value:any)=>{if(cancelled||!value?.keys?.length)return;setCatalog(mergeKeyCatalogWithBundled(value,initial));setStatus(`${value.source||"保存済み"}データを表示中`)}).catch(()=>{}).finally(()=>{if(!cancelled)setLoading(false)});api.refreshKeys?.().then((value:any)=>{if(cancelled||!value?.keys?.length)return;setCatalog(mergeKeyCatalogWithBundled(value,initial));setStatus("最新の鍵データに更新しました")}).catch(()=>{});return()=>{cancelled=true}},[]);
  useEffect(()=>{sessionStorage.setItem("tarkov-key-wiki-view",JSON.stringify({query:query.slice(0,100),mapFilter,usage,selectedId}))},[query,mapFilter,usage,selectedId]);
  const keys=Array.isArray(catalog.keys)?catalog.keys:[],mapOptions=useMemo(()=>[...new Map(keys.flatMap((key:any)=>key.mapUses||[]).map((map:any)=>[map.id,{id:map.id,name:map.name,nameEn:map.nameEn}])).values()].sort((a:any,b:any)=>String(a.name).localeCompare(String(b.name),"ja")),[keys]),visible=useMemo(()=>filterKeys(keys,{query,map:mapFilter,usage}),[keys,query,mapFilter,usage]),selected=keys.find((key:any)=>key.id===selectedId)||visible[0]||null,decision=selected?keyDecision(selected):null,taskKeyCount=keys.filter((key:any)=>key.tasks?.length).length,mapCount=new Set(keys.flatMap((key:any)=>(key.mapUses||[]).map((map:any)=>map.id))).size;
  useEffect(()=>{if(visible.length&&(!selectedId||!visible.some((key:any)=>key.id===selectedId)))setSelectedId(visible[0].id)},[visible,selectedId]);
  const clearFilters=()=>{setQuery("");setMapFilter("all");setUsage("all")};
  const lockLocation=selected?(selected.lockLocation||selected.lockLocationEn||""):"",behindLock=selected?(selected.behindLock||selected.behindLockEn||""):"",locationMaps=selected?[...new Map((selected.mapUses||[]).map((map:any)=>[map.id,map.name||map.nameEn])).values()]:[];
  return <section className="keyWiki"><header className="keyWikiHero"><div><small>KEY INTELLIGENCE</small><h2>鍵Wiki</h2><p>レイドで拾った鍵が「どこで」「どのタスクに」使えるかを、その場で判断できます。</p></div><div className="keyWikiStats"><span><b>{keys.length}</b>収録鍵</span><span><b>{taskKeyCount}</b>タスク使用</span><span><b>{mapCount}</b>対応マップ</span></div></header>
    <section className="keyWikiToolbar"><label className="keySearch"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="鍵名・タスク名・マップ名で検索…" autoComplete="off"/>{query&&<button type="button" onClick={()=>setQuery("")} aria-label="検索を消去">×</button>}</label><label><span>使用マップ</span><select value={mapFilter} onChange={event=>setMapFilter(event.target.value)}><option value="all">すべてのマップ</option>{mapOptions.map((map:any)=><option key={map.id} value={map.id}>{map.name}</option>)}</select></label><div className="keyUsageSwitch" role="group" aria-label="タスク使用で絞り込み"><button className={usage==="all"?"active":""} onClick={()=>setUsage("all")}>すべて</button><button className={usage==="task"?"active":""} onClick={()=>setUsage("task")}>タスク使用あり</button><button className={usage==="other"?"active":""} onClick={()=>setUsage("other")}>タスク使用なし</button></div></section>
    <div className="keyWikiStatus"><span>{loading?"最新データを確認中…":status}</span><b>{visible.length}件</b></div>
    <div className="keyWikiLayout"><section className="keyResults" aria-label="鍵の検索結果">{visible.length?visible.map((key:any,index:number)=>{const active=selected?.id===key.id;return <button type="button" className={active?"active":""} key={key.id} onClick={()=>setSelectedId(key.id)}><img src={key.image} alt="" loading={index===0?"eager":"lazy"} decoding="async"/><span><strong>{key.name}</strong>{normalizeKeyText(key.name)!==normalizeKeyText(key.nameEn)&&<small>{key.nameEn}</small>}<i>{(key.mapUses||[]).slice(0,2).map((map:any)=>map.name).join(" · ")||"使用マップ未登録"}</i></span><em className={key.tasks?.length?"taskUsed":""}>{key.tasks?.length?`TASK ${key.tasks.length}`:"一般用途"}</em></button>}):<div className="keyEmpty"><b>該当する鍵がありません</b><span>検索語または絞り込み条件を変更してください。</span><button type="button" onClick={clearFilters}>条件をリセット</button></div>}</section>
      <aside className="keyDetail">{selected?<><header><div className="keyDetailImage"><img src={selected.inspectImage||selected.image} onError={event=>{event.currentTarget.src=selected.image}} alt={`${selected.name}の画像`} loading="eager" decoding="async"/></div><div><small>SELECTED KEY</small><h2>{selected.name}</h2>{normalizeKeyText(selected.name)!==normalizeKeyText(selected.nameEn)&&<p>{selected.nameEn}</p>}<div className="keyDetailBadges"><span>{keyCategory(selected)}</span><span>{selected.uses>0?`最大 ${selected.uses}回使用`:"使用回数制限なし"}</span><span className={selected.tasks?.length?"important":""}>{selected.tasks?.length?`タスク ${selected.tasks.length}件で使用`:"タスク使用なし"}</span></div></div></header>
        <section className={`keyDecision ${decision?.tone||"unknown"}`}><small>QUICK DECISION</small><div><span>拾ったときの判断</span><strong>{decision?.title}</strong><p>{decision?.reason}</p></div><dl><div><dt>使用マップ</dt><dd>{selected.mapUses?.length||0}件</dd></div><div><dt>タスク</dt><dd>{selected.tasks?.length||0}件</dd></div><div><dt>耐久</dt><dd>{selected.uses>0?`最大${selected.uses}回`:"制限なし"}</dd></div></dl></section>
        <section className="keyPurpose"><small>WHAT THIS KEY IS FOR</small><h3>用途</h3><p>{selected.description||selected.descriptionEn||"用途説明を取得できませんでした。Wikiで最新情報を確認してください。"}</p>{selected.description&&selected.descriptionEn&&normalizeKeyText(selected.description)!==normalizeKeyText(selected.descriptionEn)&&<details><summary>英語の原文を表示</summary><p>{selected.descriptionEn}</p></details>}</section>
        <section className="keyWikiIntel"><article className={selected.lockLocationSource==="wiki-section"?"verified":"unlisted"}><header><div><small>LOCK LOCATION</small><h3>鍵を使う場所</h3></div><span>{selected.lockLocationSource==="wiki-section"?"Wiki掲載":"補足情報"}</span></header>{locationMaps.length>0&&<div className="keyLocationMaps" aria-label="使用場所の対応マップ"><small>対応マップ</small><div>{locationMaps.map((mapName:any)=><b key={mapName}>{mapName}</b>)}</div></div>}<p>{lockLocation||"英語Wikiに使用場所の記載がありません。"}</p>{selected.lockLocationEn&&normalizeKeyText(lockLocation)!==normalizeKeyText(selected.lockLocationEn)&&<details><summary>英語Wikiの原文を表示</summary><p>{selected.lockLocationEn}</p></details>}</article><article className={selected.behindLockSource==="wiki-section"?"verified":"unlisted"}><header><div><small>BEHIND THE LOCK</small><h3>開錠先で入手・利用できるもの</h3></div><span>{selected.behindLockSource==="wiki-section"?"Wiki掲載":"節の記載なし"}</span></header><p>{behindLock||"英語Wikiに具体的な入手物の記載がありません。"}</p>{selected.behindLockEn&&normalizeKeyText(behindLock)!==normalizeKeyText(selected.behindLockEn)&&<details><summary>英語Wikiの原文を表示</summary><p>{selected.behindLockEn}</p></details>}</article></section>
        <section className="keyTasks"><header><div><small>QUEST RELATION</small><h3>使用するタスク</h3></div><span>{selected.tasks?.length||0}件</span></header>{selected.tasks?.length?<div>{selected.tasks.map((task:any)=><button type="button" key={task.id} onClick={()=>onOpenTask(task.id,task.trader)}><b>LV.{task.level}</b><span><strong>{task.name}</strong>{normalizeKeyText(task.name)!==normalizeKeyText(task.nameEn)&&<small>{task.nameEn}</small>}<em>{task.trader}{task.map?.name?` · ${task.map.name}`:""}</em></span><i>タスク情報へ ›</i></button>)}</div>:<p>現在のタスク達成条件では、この鍵を必須とするタスクは登録されていません。</p>}</section>
        <footer><span>DATA: tarkov.dev · Escape from Tarkov Wiki</span>{selected.wiki&&<a href={selected.wiki} target="_blank" rel="noreferrer">Wikiで詳細を確認 ↗</a>}</footer></>:<div className="keyDetailEmpty">左の一覧から鍵を選択してください。</div>}</aside></div>
  </section>
}
