"use client";
import {useCallback, useEffect, useMemo, useRef, useState} from "react";
import {clampQuickSearchActive, findQuickSearchResults, resolveQuickSearchCatalog} from "./quick-search-utils.mjs";

type QuickSearchProps = {onOpenTask: (id: string, trader: string) => void; onOpenKey: (id: string) => void; onOpenExtract: (map: any, extractName: string) => void;};

export default function QuickSearch({onOpenTask, onOpenKey, onOpenExtract}: QuickSearchProps) {
  const [open, setOpen] = useState(false), [query, setQuery] = useState(""), [active, setActive] = useState(0), [catalog, setCatalog] = useState<any>(null), [loading, setLoading] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  const results = useMemo(() => findQuickSearchResults(catalog, query), [catalog, query]);
  const close = useCallback(() => {setOpen(false); setQuery(""); setActive(0);}, []);
  const choose = useCallback((entry: any) => {if (entry.kind === "task") onOpenTask(entry.taskId, entry.trader); if (entry.kind === "key") onOpenKey(entry.keyId); if (entry.kind === "extract") onOpenExtract(entry.map, entry.extractName); close();}, [close, onOpenExtract, onOpenKey, onOpenTask]);
  useEffect(() => {const onKeyDown = (event: KeyboardEvent) => {if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") {event.preventDefault(); setOpen(true); return;} if (!open) return; if (event.key === "Escape") {event.preventDefault(); close();} else if (event.key === "ArrowDown") {event.preventDefault(); setActive(old => Math.min(old + 1, Math.max(results.length - 1, 0)));} else if (event.key === "ArrowUp") {event.preventDefault(); setActive(old => Math.max(old - 1, 0));} else if (event.key === "Enter" && results[active]) {event.preventDefault(); choose(results[active]);}}; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);}, [active, choose, close, open, results]);
  useEffect(() => {if (open) {setActive(0); window.setTimeout(() => input.current?.focus(), 0);}}, [open]);
  useEffect(() => {setActive(old => clampQuickSearchActive(old, results.length));}, [results.length]);
  useEffect(() => {if (!open || catalog) return; let cancelled = false; setLoading(true); void (async () => {const [tasks, keys, maps] = await Promise.allSettled([import("./data/task-guide.json"), import("./data/key-catalog.json"), import("./data/maps-cache-v3.json")]); const fallbackTasks = tasks.status === "fulfilled" ? tasks.value.default?.tasks : undefined, fallbackKeys = keys.status === "fulfilled" ? keys.value.default?.keys : undefined, fallbackMaps = maps.status === "fulfilled" ? maps.value.default?.maps : undefined; let cachedTasks = fallbackTasks; try {const saved = JSON.parse(localStorage.getItem("tarkov-task-guide-cache") || "{}"); if (Array.isArray(saved?.tasks) && saved.tasks.length) cachedTasks = saved.tasks;} catch {} const api = window.stashAI, [savedKeys, savedMaps] = await Promise.allSettled([api?.keys?.(), api?.maps?.()]); if (!cancelled) setCatalog(resolveQuickSearchCatalog({fallbackTasks, fallbackKeys, fallbackMaps, cachedTasks, savedKeys: savedKeys.status === "fulfilled" ? savedKeys.value : undefined, savedMaps: savedMaps.status === "fulfilled" ? savedMaps.value : undefined}));})().finally(() => {if (!cancelled) setLoading(false);}); return () => {cancelled = true;};}, [catalog, open]);
  const unavailable = catalog?.unavailable || [];
  return <><button type="button" className="quickSearchButton" onClick={() => setOpen(true)} aria-label="クイック検索を開く"><span>⌕</span>検索 <kbd>Ctrl K</kbd></button>{open && <div className="quickSearchOverlay" role="presentation" onMouseDown={event => {if (event.target === event.currentTarget) close();}}><section className="quickSearchDialog" role="dialog" aria-modal="true" aria-label="クイック検索"><header><label><span>⌕</span><input ref={input} value={query} onChange={event => setQuery(event.target.value)} placeholder="タスク・鍵・脱出地点を検索" autoComplete="off" /></label><button type="button" onClick={close} aria-label="検索を閉じる">Esc</button></header>{loading ? <p className="quickSearchNotice">検索データを読み込み中…</p> : !query ? <p className="quickSearchNotice">タスク名、鍵名、脱出地点名を入力してください。空白や記号は省略して検索できます。</p> : <div className="quickSearchResults" role="listbox" aria-label="検索候補">{unavailable.length > 0 && <p className="quickSearchUnavailable">{unavailable.join("・")}の検索データを取得できませんでした。取得済みのカテゴリだけを表示しています。</p>}{results.map((entry: any, index: number) => <button type="button" role="option" aria-selected={index === active} className={index === active ? "active" : ""} key={entry.id} onMouseEnter={() => setActive(index)} onClick={() => choose(entry)}><em>{entry.label}</em><span><strong>{entry.title}</strong>{entry.subtitle && <small>{entry.subtitle}</small>}</span>{entry.mapLabel && <i>{entry.mapLabel}</i>}</button>)}{!results.length && <p className="quickSearchEmpty">{unavailable.length ? "該当する情報がありません。検索データを取得できなかったカテゴリがあります。" : "該当する情報がありません"}</p>}</div>}<footer><span>↑↓ 候補を移動</span><span>Enter で開く</span><span>Esc で閉じる</span></footer></section></div>}</>;
}
