"use client";
import {memo, useEffect, useMemo, useState} from "react";
import taskGuide from "./data/task-guide.json";
import {selectTaskReferenceImages} from "./task-media.mjs";
import {normalizeMapEntries, sameMapLocation} from "./map-normalization.mjs";
import {taskDetailRequestCache, translationRequestKey} from "./task-request-cache.mjs";
import {normalizeTaskGuideRuntime} from "./runtime-data.mjs";
import {parseStoredRecord} from "./render-safety.mjs";
import type {TaskMedia} from "./app-types";

const asset = (path: string) => typeof window !== "undefined" && window.location.protocol === "file:" ? `./${path}` : `/${path}`;
const normalizeSearchText = (value: any) => String(value ?? "").normalize("NFKC").toLocaleLowerCase("ja-JP").replace(/[^\p{L}\p{N}]/gu, "");
const taskGuideTraderOrder = ["Prapor", "Therapist", "Fence", "Skier", "Peacekeeper", "Mechanic", "Ragman", "Jaeger", "Ref"];
type MapVisual = {image: string; source: "annotated" | "raster"; size?: readonly [number, number]; revision: string;};
const mapVisuals: Record<string, MapVisual> = {
  "55f2d3fd4bdc2d5f408b4567": {image: "https://www.re3mr.com/maps/Factory/FactorybyRe3mr.png", source: "annotated", size: [13440, 6656], revision: "factory-re3mr-13440x6656-v1"},
  "56f40101d2720b2a4d8b45d6": {image: "https://maps.reemr.se/Customs/re3mrCustoms2.png", source: "annotated", size: [7832, 5016], revision: "customs-re3mr-7832x5016-v2"},
  "5704e3c2d2720bac5b8b4567": {image: "https://www.reemr.se/maps/Woods/WoodsRe3mrPNG.png", source: "annotated", size: [7680, 5168], revision: "woods-re3mr-7680x5168-v1"},
  "5704e554d2720bac5b8b456e": {image: "https://reemr.se/maps/Shoreline/re3mrShoreline2.png", source: "annotated", size: [5760, 3240], revision: "shoreline-re3mr-5760x3240-v2"},
  "5714dbc024597771384a510d": {image: "https://maps.reemr.se/Interchange/re3mrInterchange.png", source: "annotated", size: [9600, 5400], revision: "interchange-re3mr-9600x5400-v1"},
  "5b0fc42d86f7744a585f9105": {image: "https://tarkov.dev/maps/labs-2d.jpg", source: "raster", size: [3820, 1980], revision: "labs-tarkovdev-3820x1980-v1"},
  "5704e5fad2720bc05b8b4567": {image: "https://reemr.se/maps/Reserve/Re3mrReserveLossless.png", source: "annotated", size: [5760, 3240], revision: "reserve-re3mr-5760x3240-v1"},
  "5704e4dad2720bb55b8b4567": {image: "https://reemr.se/maps/Lighthouse/re3mrLighthouseVERT.png", source: "annotated", size: [8259, 7560], revision: "lighthouse-re3mr-8259x7560-v1"},
  "5714dc692459777137212e12": {image: "https://reemr.se/maps/Streets/re3mrStreetsofTarkov.png", source: "annotated", size: [7605, 4841], revision: "streets-re3mr-7605x4841-v1"},
  "653e6760052c01c1c805532f": {image: "https://www.re3mr.com/maps/Groundzero/GroundZero.png", source: "annotated", size: [2656, 2160], revision: "groundzero-re3mr-2656x2160-v1"},
  "65b8d6f5cdde2479cb2a3125": {image: "https://www.re3mr.com/maps/Groundzero/GroundZero.png", source: "annotated", size: [2656, 2160], revision: "groundzero-re3mr-2656x2160-v1"}
};
const mapBounds: Record<string, [[number, number], [number, number]]> = {
  "55f2d3fd4bdc2d5f408b4567": [[77, -64.5], [-65.5, 67.4]],
  "56f40101d2720b2a4d8b45d6": [[698, -307], [-372, 237]],
  "5704e3c2d2720bac5b8b4567": [[646, -914], [-761, 442]],
  "5704e554d2720bac5b8b456e": [[504, -415], [-1056, 618]],
  "5714dbc024597771384a510d": [[598, -442], [-433, 426]],
  "5b0fc42d86f7744a585f9105": [[-80, -477], [-287, -193]],
  "5704e5fad2720bc05b8b4567": [[289, -293], [-303, 244]],
  "5704e4dad2720bb55b8b4567": [[515, -998], [-545, 725]],
  "5714dc692459777137212e12": [[323, -295], [-280, 532]],
  "653e6760052c01c1c805532f": [[249, -124], [-99, 364]],
  "65b8d6f5cdde2479cb2a3125": [[249, -124], [-99, 364]]
};
const namedMapVisuals: Record<string, MapVisual> = {"the labyrinth": {image: "https://tarkov.dev/maps/labyrinth-2d.jpg", source: "raster", size: [4800, 4320], revision: "labyrinth-tarkovdev-4800x4320-v1"}};
const fallbackMapImages: Record<string, string> = {"55f2d3fd4bdc2d5f408b4567": "https://tarkov.dev/maps/factory-2d.jpg", "59fc81d786f774390775787e": "https://tarkov.dev/maps/factory-2d.jpg", "56f40101d2720b2a4d8b45d6": "https://tarkov.dev/maps/customs-2d.jpg", "5704e3c2d2720bac5b8b4567": "https://tarkov.dev/maps/woods-2d.jpg", "5704e554d2720bac5b8b456e": "https://www.escapistmagazine.com/wp-content/uploads/2023/07/Escape-from-Tarkov-Shoreline-Map.jpg?fit=1200%2C800", "5714dbc024597771384a510d": "https://tarkov.dev/maps/interchange-2d.jpg", "5704e4dad2720bb55b8b4567": "https://tarkov.dev/maps/lighthouse-2d.jpg", "5704e5fad2720bc05b8b4567": "https://tarkov.dev/maps/reserve-2d.jpg", "5714dc692459777137212e12": "https://tarkov.dev/maps/streets-2d.jpg", "653e6760052c01c1c805532f": "https://tarkov.dev/maps/ground-zero-2d.jpg", "65b8d6f5cdde2479cb2a3125": "https://tarkov.dev/maps/ground-zero-2d.jpg", "68236e8153654e8c1200798a": "https://tarkov.dev/maps/ground-zero-2d.jpg", "5b0fc42d86f7744a585f9105": "https://tarkov.dev/maps/labs-2d.jpg", "6a294a5b5eb5f9a1700417b7": "https://tarkov.dev/maps/labs-2d.jpg"};
const fallbackMapImagesByName: Record<string, string> = {factory: "https://tarkov.dev/maps/factory-2d.jpg", "night factory": "https://tarkov.dev/maps/factory-2d.jpg", customs: "https://tarkov.dev/maps/customs-2d.jpg", woods: "https://tarkov.dev/maps/woods-2d.jpg", shoreline: "https://tarkov.dev/maps/shoreline-2d.jpg", interchange: "https://tarkov.dev/maps/interchange-2d.jpg", lighthouse: "https://tarkov.dev/maps/lighthouse-2d.jpg", reserve: "https://tarkov.dev/maps/reserve-2d.jpg", "streets of tarkov": "https://tarkov.dev/maps/streets-2d.jpg", streets: "https://tarkov.dev/maps/streets-2d.jpg", "ground zero": "https://tarkov.dev/maps/ground-zero-2d.jpg", "ground zero 21+": "https://tarkov.dev/maps/ground-zero-2d.jpg", "ground zero tutorial": "https://tarkov.dev/maps/ground-zero-2d.jpg", "the lab": "https://tarkov.dev/maps/labs-2d.jpg", "the lab (dark)": "https://tarkov.dev/maps/labs-2d.jpg", labs: "https://tarkov.dev/maps/labs-2d.jpg", icebreaker: "https://tarkov.dev/maps/icebreaker-2d.jpg", terminal: "https://tarkov.dev/maps/terminal-2d.jpg", "the labyrinth": "https://tarkov.dev/maps/labyrinth-2d.jpg"};
const mapVisualFor = (map: any) => mapVisuals[String(map.id || "")] || namedMapVisuals[String(map.name || map.nameJa || "").trim().toLowerCase()];
const mapImageFor = (map: any) => {const id = String(map.id || ""), name = String(map.name || map.nameJa || "").trim().toLowerCase(), slug = String(map.slug || name).trim().toLowerCase().replace(/\+/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); return mapVisualFor(map)?.image || fallbackMapImages[id] || fallbackMapImagesByName[name] || fallbackMapImagesByName[String(map.slug || "").toLowerCase()] || `https://tarkov.dev/maps/${slug}-2d.jpg`;};
const taskDataRevision = "eft-1.1-live-2026-08-19";
const liveTaskCorrections: Record<string, {verifiedAt: string; note: string; removeObjectives?: string[];}> = {
  "66aa74571e5e199ecd094f18": {verifiedAt: "2026-08-18", note: "ゲーム内タスク画面（Patch 1.1）で確認", removeObjectives: ["66ab97d56cb6e3bfd7c79fbc"]}
};
function applyLiveTaskCorrections(task: any) {const correction = liveTaskCorrections[String(task?.id || "")]; if (!correction) return task; const remove = new Set(correction.removeObjectives || []); return {...task, objectives: (task.objectives || []).filter((objective: any) => !remove.has(String(objective.id))), liveVerification: {verifiedAt: correction.verifiedAt, note: correction.note, revision: taskDataRevision}};}
function normalizeTaskGuide(value: any) {const safe = normalizeTaskGuideRuntime(value, taskGuide); return {...safe, dataRevision: taskDataRevision, tasks: safe.tasks.map((rawTask: any) => {const task = applyLiveTaskCorrections(rawTask); return {...task, objectives: task.objectives.map((objective: any) => ({...objective, maps: objectiveMapsFor(task, objective)}))};})};}
const mapStages = [
  {name: "Ground Zero", ja: "グラウンドゼロ", id: "653e6760052c01c1c805532f", desc: "市街地中心部。建物内と地下通路が多く、初心者は現在地の確認が重要です。", exits: ["Emercom Checkpoint", "Mira Ave", "Nakatani Basement Stairs"]},
  {name: "Streets of Tarkov", ja: "ストリート・オブ・タルコフ", id: "5714dc692459777137212e12", desc: "広大な市街地。通り名と大きな建物を目印に移動します。", exits: ["Damaged House", "Evacuation Zone", "Klimov Street"]},
  {name: "Customs", ja: "カスタム", id: "56f40101d2720b2a4d8b45d6", desc: "道路と川で東西に分かれた定番マップ。赤倉庫・寮・新建築を覚えると迷いにくくなります。", exits: ["Crossroads", "ZB-1011", "RUAF Roadblock"]},
  {name: "Woods", ja: "ウッズ", id: "5704e3c2d2720bac5b8b4567", desc: "森林中心のマップ。山・湖・製材所・送電線で方向を確認します。", exits: ["Outskirts", "UN Roadblock", "ZB-014"]},
  {name: "Interchange", ja: "インターチェンジ", id: "5714dbc024597771384a510d", desc: "巨大商業施設ULTRAが中心。店舗名と屋外の方角をセットで覚えます。", exits: ["Emercom Checkpoint", "Railway Exfil", "Hole in the Fence"]},
  {name: "Factory", ja: "ファクトリー", id: "55f2d3fd4bdc2d5f408b4567", desc: "小規模な屋内戦マップ。扉番号・地下・オフィス階段が主な目印です。", exits: ["Gate 3", "Cellars", "Med Tent Gates"]},
  {name: "Reserve", ja: "リザーブ", id: "5704e5fad2720bc05b8b4567", desc: "軍事基地。建物のチェス記号と地下通路を覚えると移動しやすくなります。", exits: ["D-2", "Cliff Descent", "Armored Train"]},
  {name: "Lighthouse", ja: "ライトハウス", id: "5704e4dad2720bb55b8b4567", desc: "海岸沿いに細長いマップ。幹線道路・山側・浄水場の位置関係が重要です。", exits: ["Path to Shoreline", "Northern Checkpoint", "Southern Road"]},
  {name: "Shoreline", ja: "ショアライン", id: "5704e554d2720bac5b8b456e", desc: "保養所を中心とした広い自然マップ。海岸・川・発電所で方角を確認します。", exits: ["Path to Lighthouse", "Road to Customs", "Tunnel"]},
  {name: "The Lab", ja: "研究所", id: "5b0fc42d86f7744a585f9105", desc: "高難度の屋内施設。各区画の色とエレベーター、電源操作を確認します。", exits: ["Cargo Elevator", "Medical Block Elevator", "Parking Gate"]},
  {name: "Terminal", ja: "ターミナル", id: "", desc: "港湾ターミナル。遮蔽物と建物番号を確認して移動します。", exits: []},
  {name: "Icebreaker", ja: "アイスブレーカー", id: "", desc: "船内を進む特殊マップ。甲板・機関室・通路階層を確認します。", exits: []},
  {name: "The Labyrinth", ja: "ラビリンス", id: "", desc: "複雑な閉所マップ。入口、分岐、階層を一つずつ確認します。", exits: []}
];
function mapStageFor(reference: any) {return mapStages.find(stage => sameMapLocation(stage, typeof reference === "string" ? {name: reference} : reference));}
function taskLocations(task: any) {const entries = [...(task.map ? [{id: task.mapId, name: task.map, nameJa: task.mapJa}] : []), ...(task.objectives || []).flatMap((objective: any) => objective.maps || [])]; return normalizeMapEntries(entries).filter((map: any) => map.name).map((map: any) => ({name: map.name, label: map.label, id: map.id})) as Array<{name: string; label: string; id: string;}>;}
function taskLocationLabel(task: any) {const locations = taskLocations(task); return locations.length === 0 ? "ANY MAP" : locations.length === 1 ? locations[0].label : `複数マップ（${locations.length}）`;}
function objectiveMapsFor(task: any, objective: any) {if (Array.isArray(objective.maps) && objective.maps.length) return normalizeMapEntries(objective.maps); if (!task.map) return []; const stage = mapStageFor({id: task.mapId, name: task.map, nameJa: task.mapJa}); return normalizeMapEntries([{id: stage?.id || task.mapId || "", name: task.map, nameJa: task.mapJa || task.map, slug: String(task.map).toLowerCase().replace(/[^a-z0-9]+/g, "-")}]);}
function taskMapReferences(task: any) {const entries = [...(task.objectives || []).flatMap((objective: any) => objective.maps || []), ...(task.map ? [{id: task.mapId, name: task.map, nameJa: task.mapJa}] : [])]; return normalizeMapEntries(entries).filter((map: any) => map.name);}
export default function TaskGuidePage() {
  const restored = useMemo(() => {if (typeof window === "undefined") return {} as any; const saved=parseStoredRecord(sessionStorage.getItem("tarkov-task-last-view")),current=history.state; return current?.stashPage === "guide" && current?.guideView ? {...saved, guideView: current.guideView, selected: current.guideSelected || "", selectedTrader: current.guideTrader || ""} : saved;}, []);
  const [section, setSection] = useState<"story" | "tasks" | "battle">((history.state?.guideSection === "tasks" ? "tasks" : (["story", "tasks", "battle"].includes(restored.section) ? restored.section : "tasks")) as any), [search, setSearch] = useState(String(restored.search || "").slice(0, 100)), [selected, setSelected] = useState(String(restored.selected || "")), [selectedTrader, setSelectedTrader] = useState(String(restored.selectedTrader || "")), [guideView, setGuideView] = useState<"traders" | "directory" | "list" | "detail">((["traders", "directory", "list", "detail"].includes(restored.guideView) ? restored.guideView : "traders") as any), [taskSort, setTaskSort] = useState<"recommended" | "level" | "name">(restored.taskSort || "recommended"), [taskGroup, setTaskGroup] = useState<"none" | "map" | "trader">(restored.taskGroup || "none"), [mapFilter, setMapFilter] = useState(String(restored.mapFilter || "all")), [guide, setGuide] = useState<any>(() => normalizeTaskGuide(taskGuide)), [portraits, setPortraits] = useState<Record<string, string>>({}), [updating, setUpdating] = useState(false), [updateMessage, setUpdateMessage] = useState("");
  useEffect(() => {try {sessionStorage.setItem("tarkov-task-last-view", JSON.stringify({section, search: search.slice(0, 100), selected, selectedTrader, guideView, taskSort, taskGroup, mapFilter}));} catch {}}, [section, search, selected, selectedTrader, guideView, taskSort, taskGroup, mapFilter]);
  useEffect(() => {const restore = (event: PopStateEvent) => {if (event.state?.stashPage !== "guide" || !event.state?.guideView) return; setGuideView(event.state.guideView); setSelected(event.state.guideSelected || ""); setSelectedTrader(event.state.guideTrader || ""); setSearch("");}; window.addEventListener("popstate", restore); return () => window.removeEventListener("popstate", restore);}, []);
  useEffect(() => {try {const cached = localStorage.getItem("tarkov-task-guide-cache"); if (cached) {const normalized = normalizeTaskGuide(JSON.parse(cached)); setGuide(normalized); localStorage.setItem("tarkov-task-guide-cache", JSON.stringify(normalized));} } catch {} }, []);
  useEffect(() => {const names = ["Prapor", "Therapist", "Fence", "Skier", "Peacekeeper", "Mechanic", "Ragman", "Jaeger", "Ref"]; let cached: Record<string, string> = {}; try {cached = JSON.parse(localStorage.getItem("tarkov-trader-portraits") || "{}"); setPortraits(cached);} catch {} if (window.stashAI?.traderPortraits) window.stashAI.traderPortraits(names).then(found => {const next = {...cached, ...found}; setPortraits(next); localStorage.setItem("tarkov-trader-portraits", JSON.stringify(next));}).catch(() => {});}, []);
  const refresh = async () => {
    setUpdating(true); setUpdateMessage("最新データを取得しています…"); try {
      const base = "https://json.tarkov.dev/regular/", names = ["tasks", "tasks_en", "tasks_ja", "traders", "traders_en", "maps", "maps_en", "maps_ja", "items", "items_en", "items_ja"], docs = await Promise.all(names.map(async name => {const response = await fetch(base + name); if (!response.ok) throw Error(`${name}: ${response.status}`); return response.json();})), [raw, en, ja, traderDoc, traderEn, mapDoc, mapEn, mapJa, itemDoc, itemEn, itemJa] = docs, traderMap = traderDoc.data.traders || traderDoc.data, mapMap = mapDoc.data.maps || mapDoc.data, itemMap = itemDoc.data.items || itemDoc.data, oldById = new Map(guide.tasks.map((x: any) => [x.id, x])), tr = (table: any, key: string, fallback = "") => table?.data?.[key] || fallback;
      const tradersById = (id: string) => {const t = traderMap[id] || Object.values(traderMap).find((x: any) => x.id === id) as any; return tr(traderEn, t?.name || `${id} name`, t?.normalizedName || "Other");}, mapNames = (id: string) => {const m = mapMap[id] || Object.values(mapMap).find((x: any) => x.id === id) as any; return {id, name: tr(mapEn, m?.name || `${id} Name`, m?.normalizedName || ""), nameJa: tr(mapJa, m?.name || `${id} Name`, "")};};
      const itemInfo = (value: any) => {const id = String(typeof value === "string" ? value : value?.id || value?.item || ""); const rawItem: any = itemMap[id] || Object.values(itemMap).find((entry: any) => entry.id === id) || {}; return {id, name: tr(itemEn, `${id} Name`, rawItem.name || rawItem._name || id), nameJa: tr(itemJa, `${id} Name`, ""), shortName: tr(itemEn, `${id} ShortName`, rawItem.shortName || rawItem._shortName || id), image: `https://assets.tarkov.dev/${id}-grid-image.webp`};};
      const tasks = Object.values(raw.data.tasks).map((task: any) => {const old: any = oldById.get(task.id) || {}, taskMap = mapNames(task.map), oldObjectives = new Map((old.objectives || []).map((objective: any) => [objective.id, objective])); return applyLiveTaskCorrections({...old, id: task.id, name: tr(en, `${task.id} name`, task.name), nameJa: tr(ja, `${task.id} name`, ""), trader: tradersById(task.trader), level: task.minPlayerLevel || 1, image: task.taskImageLink || old.image || "", wiki: task.wikiLink || old.wiki || "", map: taskMap.name, mapJa: taskMap.nameJa, mapId: taskMap.id, prerequisites: (task.taskRequirements || []).map((r: any) => ({id: r.task, name: tr(en, `${r.task} name`, r.task), nameJa: tr(ja, `${r.task} name`, ""), status: r.status || []})), objectives: (task.objectives || []).map((o: any) => {const oldObjective: any = oldObjectives.get(o.id) || {}; return {id: o.id, type: o.type, description: tr(en, o.description, tr(en, o.id, o.type)), descriptionJa: tr(ja, o.description, tr(ja, o.id, "")), count: o.count || 1, foundInRaid: !!o.foundInRaid, maps: (o.maps || []).map(mapNames), zones: Array.isArray(o.zones) && o.zones.length ? o.zones : (oldObjective.zones || []), items: (o.items || []).slice(0, 12).map(itemInfo)};})});});
      const next = normalizeTaskGuide({...guide, dataSource: "json.tarkov.dev + game-confirmed corrections", updatedAt: new Date().toISOString(), tasks}); setGuide(next); localStorage.setItem("tarkov-task-guide-cache", JSON.stringify(next)); taskDetailRequestCache.clear(); setUpdateMessage(`${tasks.length}件を更新しました（ゲーム内確認済み補正を適用）`);
    } catch (error) {console.error(error); setUpdateMessage("更新できませんでした。インターネット接続を確認してください。");} finally {setUpdating(false);}
  };
  const traderFace: Record<string, string> = {Prapor: asset("traders/faces/prapor.png"), Therapist: asset("traders/faces/therapist.png"), Fence: asset("traders/faces/fence.png"), Skier: asset("traders/faces/skier.png"), Peacekeeper: asset("traders/faces/peacekeeper.png"), Mechanic: asset("traders/faces/mechanic.png"), Ragman: asset("traders/faces/ragman.png"), Jaeger: asset("traders/faces/jaeger.png"), Ref: "https://tarkov.dev/images/traders/ref.jpg"};
  const taskSearchIndex = useMemo(() => guide.tasks.map((task: any) => {const locations = taskLocations(task); return {task, locations, searchText: normalizeSearchText(`${task.nameJa || ""} ${task.name || ""} ${task.trader || ""} ${locations.map(map => `${map.name} ${map.label}`).join(" ")}`)};}), [guide.tasks]);
  const mapOptions = useMemo(() => [...new Map(taskSearchIndex.flatMap(entry => entry.locations).map((map: any) => [map.id || map.name, {value: map.id || map.name, label: map.label}])).values()].sort((a: any, b: any) => a.label.localeCompare(b.label, "ja")), [taskSearchIndex]);
  const traderTaskCounts = useMemo(() => taskSearchIndex.reduce((counts: Record<string, number>, {task}: any) => ({...counts, [task.trader]: (counts[task.trader] || 0) + 1}), {}), [taskSearchIndex]);
  const q = useMemo(() => normalizeSearchText(search), [search]);
  const {searched, directoryTasks, visibleTasks} = useMemo(() => {
    const searchedEntries = q ? taskSearchIndex.filter(entry => entry.searchText.includes(q)) : taskSearchIndex, filteredEntries = searchedEntries.filter(entry => mapFilter === "all" || (mapFilter === "any" ? !entry.locations.length : entry.locations.some(map => map.id === mapFilter || map.name === mapFilter)));
    const sortTasks = (entries: typeof filteredEntries) => entries.map(entry => entry.task).sort((a, b) => {const byName = String(a.name || "").localeCompare(String(b.name || ""), "en", {sensitivity: "base"}); if (taskSort === "name") return byName; const byLevel = Number(a.level || 0) - Number(b.level || 0); if (taskSort === "level") return byLevel || byName; const byPrerequisite = (a.prerequisites?.length || 0) - (b.prerequisites?.length || 0), byTrader = taskGuideTraderOrder.indexOf(a.trader) - taskGuideTraderOrder.indexOf(b.trader); return byLevel || byPrerequisite || byTrader || byName;});
    return {searched: searchedEntries.map(entry => entry.task), directoryTasks: sortTasks(filteredEntries), visibleTasks: sortTasks(filteredEntries.filter(entry => !selectedTrader || entry.task.trader === selectedTrader))};
  }, [mapFilter, q, selectedTrader, taskSearchIndex, taskSort]);
  const active = useMemo(() => guide.tasks.find((task: any) => task.id === selected), [guide.tasks, selected]);
  const openGuide = (view: "traders" | "directory" | "list" | "detail", taskId = selected, trader = selectedTrader) => {history.pushState({...history.state, stashPage: "guide", guideView: view, guideSelected: taskId, guideTrader: trader}, ""); setGuideView(view); setSelected(taskId); setSelectedTrader(trader);};
  const searchCount = useMemo(() => section === "tasks" ? searched.length : section === "story" ? guide.story.filter((entry: any) => !q || normalizeSearchText(entry.name).includes(q)).length : guide.battlePass.filter((entry: any) => !q || normalizeSearchText(entry.name).includes(q)).length, [guide.battlePass, guide.story, q, searched.length, section]);
  return <section className="manager taskGuide"><div className="guideHeader"><div><span>04 / TASK INTELLIGENCE</span><h2>タスク情報</h2><p>目的・準備・場所をひとつの画面で確認。</p></div><div className="guideUpdate"><small>最終更新 {new Date(guide.updatedAt).toLocaleString("ja-JP")}</small><button onClick={refresh} disabled={updating}>{updating ? "更新中…" : "↻ 最新情報に更新"}</button>{updateMessage && <em>{updateMessage}</em>}</div></div><div className="guideTabs"><button className={section === "story" ? "active" : ""} onClick={() => setSection("story")}>ストーリータスク</button><button className={section === "tasks" ? "active" : ""} onClick={() => setSection("tasks")}>サブタスク</button><button className={section === "battle" ? "active" : ""} onClick={() => setSection("battle")}>バトルパス</button></div><label className="questHomeSearch taskGlobalSearch"><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="タスク名・トレーダー名で検索…" autoComplete="off" /><b>{search ? `${searchCount}件` : "タスク内を検索"}</b>{search && <button type="button" onClick={() => setSearch("")}>×</button>}</label>
    {section === "tasks" && <section className="questBrowser">{search ? <>
      <TaskDirectoryControls mode={guideView} onMode={mode => openGuide(mode, "", "")} sort={taskSort} onSort={setTaskSort} group={taskGroup} onGroup={setTaskGroup} mapFilter={mapFilter} onMapFilter={setMapFilter} maps={mapOptions} />
      <GuideTaskList title="検索結果" subtitle="すべてのトレーダー" tasks={directoryTasks} groupBy={taskGroup} sort={taskSort} onSelect={task => {setSearch(""); openGuide("detail", task.id, task.trader);}} />
    </> : <>
      {guideView === "traders" && <><TaskDirectoryControls mode={guideView} onMode={mode => openGuide(mode, "", "")} sort={taskSort} onSort={setTaskSort} group={taskGroup} onGroup={setTaskGroup} mapFilter={mapFilter} onMapFilter={setMapFilter} maps={mapOptions} /><div className="traderPortraitGrid">{taskGuideTraderOrder.map(trader => {const portrait = traderFace[trader] || portraits[trader]; return <button key={trader} onClick={() => {setSearch(""); openGuide("list", "", trader);}}><div>{portrait ? <img src={portrait} alt={`${trader}の顔写真`} loading="lazy" decoding="async" /> : <span className="portraitLoading">肖像<br />読込中</span>}<i>{traderTaskCounts[trader] || 0}</i></div><strong>{trader}</strong><small>タスク一覧を見る　→</small></button>;})}</div></>}
      {guideView === "directory" && <><TaskDirectoryControls mode={guideView} onMode={mode => openGuide(mode, "", "")} sort={taskSort} onSort={setTaskSort} group={taskGroup} onGroup={setTaskGroup} mapFilter={mapFilter} onMapFilter={setMapFilter} maps={mapOptions} /><GuideTaskList title="すべてのサブタスク" subtitle="マップ・トレーダーを横断して表示" tasks={directoryTasks} groupBy={taskGroup} sort={taskSort} onSelect={task => openGuide("detail", task.id, task.trader)} /></>}
      {guideView === "list" && <><GuideBreadcrumb onBack={() => history.back()} onHome={() => {setSearch(""); openGuide("traders", "", "");}} label="ひとつ前へ戻る" title={selectedTrader} /><TaskDirectoryControls mode={guideView} onMode={mode => openGuide(mode, "", "")} sort={taskSort} onSort={setTaskSort} group={taskGroup} onGroup={setTaskGroup} mapFilter={mapFilter} onMapFilter={setMapFilter} maps={mapOptions} /><GuideTaskList title={`${selectedTrader}のタスク`} subtitle="指定条件で表示" tasks={visibleTasks} groupBy={taskGroup} sort={taskSort} onSelect={task => openGuide("detail", task.id, selectedTrader || task.trader)} /></>}
      {guideView === "detail" && active && <><GuideBreadcrumb onBack={() => {setSearch(""); if (selectedTrader) openGuide("list", "", selectedTrader); else openGuide("directory", "", "");}} onHome={() => {setSearch(""); openGuide("traders", "", "");}} label={selectedTrader ? `${selectedTrader}の一覧へ戻る` : "タスク一覧へ戻る"} title={active.name} /><TaskDetail task={active} /></>}
    </>}</section>}
    {section === "story" && <div className="storyGuideGrid">{guide.story.filter((x: any) => !q || normalizeSearchText(x.name).includes(q)).map((story: any) => <article key={story.id}><div className="chapterNo">CHAPTER {String(story.chapter).padStart(2, "0")}</div><h3>{story.name}</h3><p>{story.summary}</p><a href={story.source} target="_blank" rel="noreferrer">情報源を開く ↗</a></article>)}</div>}
    {section === "battle" && <div className="battleGuide">{guide.battlePass.filter((x: any) => !q || normalizeSearchText(x.name).includes(q)).map((pass: any) => <article key={pass.id}><div className="battleVisual"><span>BATTLE<br />PASS</span><b>{pass.season}</b></div><div><small>{pass.season}</small><h3>{pass.name}</h3><p>{pass.summary}</p><ol>{pass.objectives.map((objective: string) => <li key={objective}>{objective}</li>)}</ol><a href={pass.source} target="_blank" rel="noreferrer">シーズン情報を確認 ↗</a></div></article>)}</div>}
  </section>;
}
function GuideBreadcrumb({onBack, onHome, label, title}: {onBack: () => void, onHome?: () => void, label: string, title: string;}) {return <div className="guideBreadcrumb"><div className="guideNavButtons"><button type="button" onClick={onBack}><span>←</span>{label}</button>{onHome && <button type="button" className="guideHomeButton" onClick={onHome}><span>⌂</span>タスクTOPへ戻る</button>}</div><div className="guideCurrent"><small>CURRENT PAGE</small><strong>{title}</strong></div></div>;}
function TaskDirectoryControls({mode, onMode, sort, onSort, group, onGroup, mapFilter, onMapFilter, maps}: {mode: string; onMode: (mode: "traders" | "directory") => void; sort: "recommended" | "level" | "name"; onSort: (value: any) => void; group: "none" | "map" | "trader"; onGroup: (value: any) => void; mapFilter: string; onMapFilter: (value: string) => void; maps: Array<{value: string; label: string;}>;}) {return <section className="taskDirectoryControls" aria-label="サブタスクの表示設定"><div className="taskViewSwitch"><button type="button" className={mode === "traders" ? "active" : ""} onClick={() => onMode("traders")}>トレーダーから探す</button><button type="button" className={mode !== "traders" ? "active" : ""} onClick={() => onMode("directory")}>全タスクから探す</button></div><label><span>並べ替え</span><select value={sort} onChange={event => onSort(event.target.value)}><option value="recommended">推奨順</option><option value="level">レベル順</option><option value="name">名前順 A–Z</option></select></label><label><span>グループ</span><select value={group} onChange={event => onGroup(event.target.value)}><option value="none">グループなし</option><option value="map">マップ別</option><option value="trader">トレーダー別</option></select></label><label><span>マップ</span><select value={mapFilter} onChange={event => onMapFilter(event.target.value)}><option value="all">すべてのマップ</option><option value="any">場所指定なし（ANY MAP）</option>{maps.map(map => <option key={map.value} value={map.value}>{map.label}</option>)}</select></label></section>;}
function GuideTaskList({title, subtitle, tasks, groupBy, sort, onSelect}: {title: string; subtitle: string; tasks: any[]; groupBy: "none" | "map" | "trader"; sort: "recommended" | "level" | "name"; onSelect: (task: any) => void;}) {const groups = groupBy === "none" ? [["", tasks]] : [...tasks.reduce((result: Map<string, any[]>, task: any) => {const key = groupBy === "map" ? (taskLocations(task).length ? taskLocationLabel(task) : "場所指定なし（ANY MAP）") : (task.trader || "トレーダー不明"), current = result.get(key) || []; current.push(task); result.set(key, current); return result;}, new Map<string, any[]>()).entries()].sort(([a], [b]) => {if (a.includes("ANY MAP")) return 1; if (b.includes("ANY MAP")) return -1; return a.localeCompare(b, "ja");}), badge = sort === "name" ? "A → Z" : sort === "level" ? "LEVEL" : "RECOMMENDED", cards = (list: any[]) => <div className="guideTaskCards">{list.map(task => <button key={task.id} onClick={() => onSelect(task)}><span>LV.{task.level}</span><div><strong>{task.name}</strong><em>{task.trader} · {taskLocationLabel(task)}</em></div><i>›</i></button>)}</div>; return <section className="guideTaskDirectory"><header><div><small>TASK DIRECTORY</small><h2>{title}</h2><p>{subtitle} · {tasks.length}件</p></div><b>{badge}</b></header>{tasks.length ? <div className="guideTaskGroups">{groups.map(([name, list]: any) => <section key={name || "all"}>{name && <header><strong>{name}</strong><span>{list.length}件</span></header>}{cards(list)}</section>)}</div> : <div className="guideEmpty">該当するタスクがありません。マップ条件を変更してください。</div>}</section>;}
const TaskDetail = memo(function TaskDetail({task}: {task: any;}) {
  const objectiveLabel: Record<string, string> = {giveItem: "納品", findItem: "発見", shoot: "討伐", extract: "脱出", visit: "探索", mark: "設置", plantItem: "設置", buildItem: "組立", useItem: "使用"};
  const [media, setMedia] = useState<TaskMedia[]>([]), [mediaLoading, setMediaLoading] = useState(false), [lightbox, setLightbox] = useState<TaskMedia | null>(null), [mapView, setMapView] = useState<any>(null), [translations, setTranslations] = useState<Record<string, string>>({}), [translating, setTranslating] = useState(false), [requiredKeys, setRequiredKeys] = useState<any[]>([]), [requirementsLoading, setRequirementsLoading] = useState(true), [requirementsVerified, setRequirementsVerified] = useState(false), [weaponBuilds, setWeaponBuilds] = useState<any[]>([]), [weaponBuildLoading, setWeaponBuildLoading] = useState(false), [weaponBuildVerified, setWeaponBuildVerified] = useState(false);
  const hasJapanese = (value: string) => /[ぁ-んァ-ヶ一-龠々]/.test(value || ""), jp = (localized: string, english: string) => hasJapanese(localized) ? localized : translations[english] || localized || english;
  useEffect(() => {let cancelled = false; setMedia([]); setMediaLoading(!!task.wiki); if (window.stashAI && task.wiki) window.stashAI.media(task.wiki).then(images => {if (!cancelled) setMedia(selectTaskReferenceImages(images, task));}).catch(() => {if (!cancelled) setMedia([]);}).finally(() => {if (!cancelled) setMediaLoading(false);}); else setMediaLoading(false); return () => {cancelled = true;};}, [task.id, task.wiki, task.name]);
  useEffect(() => {let cancelled = false; setRequiredKeys([]); setRequirementsLoading(true); setRequirementsVerified(false); const request = window.stashAI?.requirements; if (request) taskDetailRequestCache.get(`requirements:${task.id}`, () => request(task.id), result => !!result?.verified).then(result => {if (cancelled) return; const validKeys = (result.keys || []).filter((key: any) => key?.id && key.name && key.name !== key.id && key.shortName !== key.id); setRequiredKeys(validKeys); setRequirementsVerified(!!result.verified);}).catch(() => {}).finally(() => {if (!cancelled) setRequirementsLoading(false);}); else setRequirementsLoading(false); return () => {cancelled = true;};}, [task.id]);
  useEffect(() => {let cancelled = false; const hasBuild = (task.objectives || []).some((objective: any) => objective.type === "buildWeapon" || objective.type === "buildItem"); setWeaponBuilds([]); setWeaponBuildVerified(false); if (!hasBuild) {setWeaponBuildLoading(false); return () => {cancelled = true;};} setWeaponBuildLoading(true); const request = window.stashAI?.weaponBuild; if (request) taskDetailRequestCache.get(`weapon-build:${task.id}`, () => request(task.id), result => !!result?.verified).then(result => {if (cancelled) return; setWeaponBuilds(result.builds || []); setWeaponBuildVerified(!!result.verified);}).catch(() => {}).finally(() => {if (!cancelled) setWeaponBuildLoading(false);}); else setWeaponBuildLoading(false); return () => {cancelled = true;};}, [task.id]);
  useEffect(() => {let cancelled = false; let cached: Record<string, string> = {}; try {cached = JSON.parse(localStorage.getItem("tarkov-ja-translations") || "{}");} catch {} setTranslations(cached); const candidates = [...(task.objectives || []).map((x: any) => x.description)].filter((text: string, index: number, list: string[]) => text && !hasJapanese(text) && list.indexOf(text) === index && !cached[text]); const request = window.stashAI?.translate; if (candidates.length && request) {setTranslating(true); taskDetailRequestCache.get(`translate:${translationRequestKey(candidates)}`, () => request(candidates), result => candidates.every(text => result?.[text] && result[text] !== text)).then(result => {if (cancelled) return; const usable = Object.fromEntries(Object.entries(result).filter(([en, ja]) => ja && ja !== en && hasJapanese(ja))); const next = {...cached, ...usable}; setTranslations(next); localStorage.setItem("tarkov-ja-translations", JSON.stringify(next));}).catch(() => {}).finally(() => {if (!cancelled) setTranslating(false);});} return () => {cancelled = true;};}, [task.id]);
  useEffect(() => {if (!lightbox && !mapView) return; const close = (event: KeyboardEvent) => {if (event.key === "Escape") {setLightbox(null); setMapView(null);} }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close);}, [lightbox, mapView]);
  const allObjectiveItems = (task.objectives || []).flatMap((objective: any) => (objective.items || []).map((item: any) => ({...item, objective}))), bringItems = allObjectiveItems.filter(({objective}: any) => ["plantItem", "mark", "useItem", "buildItem"].includes(objective.type)), turnInItems = allObjectiveItems.filter(({objective}: any) => ["giveItem", "findItem"].includes(objective.type)), groupItems = (entries: any[]) => {const grouped = new Map<string, {item: any; objectives: any[];}>(); for (const entry of entries) {const key = String(entry.id || entry.name || entry.shortName), current = grouped.get(key) || {item: entry, objectives: []}; if (!current.objectives.some(objective => objective.id === entry.objective.id)) current.objectives.push(entry.objective); grouped.set(key, current);} return [...grouped.values()];}, bringGroups = groupItems(bringItems), turnInGroups = groupItems(turnInItems), showPreparation = requiredKeys.length > 0 || bringGroups.length > 0 || turnInGroups.length > 0, conditionObjectives = (task.objectives || []).filter((objective: any) => ["shoot", "extract", "buildItem", "useItem"].includes(objective.type)), visualObjectiveTypes = new Set(["visit", "mark", "plantItem", "extract", "findQuestItem", "questItem"]), needsLocationImages = (task.objectives || []).some((objective: any) => visualObjectiveTypes.has(objective.type) || objective.zones?.some((zone: any) => zone.position)), taskMaps = taskMapReferences(task).map((map: any) => {const objectives = (task.objectives || []).filter((objective: any) => (objective.maps || []).some((candidate: any) => sameMapLocation(candidate, map))), objective = objectives.find((entry: any) => entry.zones?.some((zone: any) => zone.position)) || objectives[0] || task.objectives?.[0], mapIds = map.sourceIds || [map.id], zone = objective?.zones?.find((entry: any) => mapIds.includes(entry.map) && entry.position) || objective?.zones?.find((entry: any) => entry.position); return {map, objectives, objective, zone};});
  const openObjectiveMap = (map: any, zone: any, objective: any, description: string) => setMapView({map, zone, description, objectiveId: objective?.id || "", taskId: task.id, taskName: task.name}), openTaskMap = ({map, objective, zone}: any) => openObjectiveMap(map, zone, objective, objective ? jp(objective.descriptionJa, objective.description) : task.name);
  return <article className={`taskDetail ${needsLocationImages ? "hasLocationObjectives" : "noLocationObjectives"}`}>
    {conditionObjectives.some((objective: any) => objective.type === "shoot") && <section className="killObjectiveSummary"><header><small>ELIMINATION TARGET</small><h3>討伐目標</h3></header><div>{conditionObjectives.filter((objective: any) => objective.type === "shoot").map((objective: any) => <article key={objective.id}><span>倒す人数</span><strong>{Number(objective.count || 1).toLocaleString()}</strong><b>体</b><p>{jp(objective.descriptionJa, objective.description)}</p></article>)}</div></section>}
    {(task.objectives || []).some((objective: any) => objective.type === "buildWeapon" || objective.type === "buildItem") && <WeaponBuildGuide builds={weaponBuilds} loading={weaponBuildLoading} verified={weaponBuildVerified} wiki={task.wiki} />}
    <div className="taskHero">{task.image && <img src={task.image} alt="" loading="eager" decoding="async" />}<div><small>{task.trader} · LV.{task.level}{translating ? " · 説明を日本語へ翻訳中…" : ""}</small><h2>{task.name}</h2>{task.liveVerification && <div className="taskMeta"><span className="liveVerified">✓ PATCH 1.1 ゲーム内確認済み</span></div>}</div></div>
    {task.prerequisites?.length > 0 && <section className="prerequisites"><h3>解放条件</h3>{task.prerequisites.map((x: any) => <span key={x.id}>{x.name}</span>)}</section>}
    {showPreparation && <section className="taskPreparation"><div className="detailTitle"><small>BEFORE YOU RAID</small><h3>必要な準備・納品</h3><p>このタスクで実際に必要なものだけを表示しています。</p></div><div className="preparationGrid">{requiredKeys.length > 0 && <article className="prepKeys"><header><span>01</span><div><small>ACCESS</small><h4>必要な鍵</h4></div></header><div className="prepItems">{requiredKeys.map(key => <div key={`${key.objectiveId || "task"}-${key.id}`}><img src={key.image || `https://assets.tarkov.dev/${key.id}-grid-image.webp`} alt="" loading="lazy" decoding="async" /><span><b>{key.nameJa || key.shortName || key.name}</b>{key.nameJa && <small>{key.name}</small>}</span><em>必要</em></div>)}</div></article>}{bringGroups.length > 0 && <article className="prepBring"><header><span>02</span><div><small>TAKE INTO RAID</small><h4>持っていく物</h4></div></header><div className="prepItems">{bringGroups.map(({item, objectives}: any) => <div key={item.id || item.name}><img src={item.image || `https://assets.tarkov.dev/${item.id}-grid-image.webp`} alt="" loading="lazy" decoding="async" /><span><b>{item.nameJa || item.shortName || item.name || "指定アイテム"}</b>{objectives.map((objective: any) => <small key={objective.id}>・{objective.count || 1}個持っていく — {jp(objective.descriptionJa, objective.description)}</small>)}</span><em>持込</em></div>)}</div></article>}{turnInGroups.length > 0 && <article className="prepTurnIn"><header><span>03</span><div><small>OBTAIN / HAND OVER</small><h4>入手・納品する物</h4></div></header><div className="prepItems">{turnInGroups.map(({item, objectives}: any) => {const found = objectives.filter((objective: any) => objective.type === "findItem"), handOver = objectives.filter((objective: any) => objective.type === "giveItem"), displayCount = Math.max(1, ...objectives.map((objective: any) => Number(objective.count) || 1)); return <div key={item.id || item.name}><img src={item.image || `https://assets.tarkov.dev/${item.id}-grid-image.webp`} alt="" loading="lazy" decoding="async" /><span><b>{item.nameJa || item.shortName || item.name || "指定アイテム"} ×{displayCount}</b>{found.map((objective: any) => <small key={objective.id}>・レイドで{objective.count || 1}個見つける{objective.foundInRaid ? "（FIR）" : ""}</small>)}{handOver.map((objective: any) => <small key={objective.id}>・{objective.count || 1}個納品する{objective.foundInRaid ? "（FIR）" : ""}</small>)}</span><em className={objectives.some((objective: any) => objective.foundInRaid) ? "firRequired" : ""}>{objectives.some((objective: any) => objective.foundInRaid) ? "FIR" : "納品"}</em></div>;})}</div></article>}</div></section>}
    {(taskMaps.length > 0 || task.wiki) && <section className="taskMaps"><div className="detailTitle"><small>TASK MAPS</small><h3>関連マップ・攻略</h3><p>タスク全体に関係するマップと攻略画像を、手順に入る前にまとめています。</p></div>{taskMaps.length > 0 && <div className="taskMapList">{taskMaps.map(({map, objectives, objective, zone}: any) => <button type="button" className="taskMapButton" key={map.id || map.name} onClick={() => openTaskMap({map, objective, zone})}><span>⌖ MAP</span><strong>{map.nameJa || map.name}</strong><small>{objectives.length ? `対象手順 ${objectives.map((entry: any) => String((task.objectives || []).indexOf(entry) + 1).padStart(2, "0")).join("・")}` : "このタスクの対象マップ"}</small></button>)}</div>}{task.wiki && <a className="taskSpecificMap" href={task.wiki} target="_blank" rel="noreferrer">このタスク専用の攻略ページ・画像を確認 ↗</a>}</section>}
    <section className="objectiveSection"><div className="detailTitle"><small>STEP BY STEP</small><h3>達成手順・目的地点</h3></div>{task.objectives.map((objective: any, index: number) => {const description = jp(objective.descriptionJa, objective.description); return <div className="objectiveCard" key={objective.id}><b>{String(index + 1).padStart(2, "0")}</b><div><small>{objectiveLabel[objective.type] || objective.type}{objective.count > 1 ? ` ×${objective.count}` : ""}{objective.foundInRaid ? " · FIR" : ""}</small><h4>{description}</h4>{description !== objective.description && <p>{objective.description}</p>}{objective.zones?.some((zone: any) => zone.position) && <div className="zoneCoordinates">{objective.zones.filter((zone: any) => zone.position).slice(0, 3).map((zone: any) => <span key={`${zone.id}-${zone.map}`}>目的地点座標　X {zone.position.x.toFixed(1)} / Z {zone.position.z.toFixed(1)}</span>)}</div>}{objective.items?.length > 0 && <div className="guideItems">{objective.items.map((item: any) => <div key={item.id}><img src={item.image || `https://assets.tarkov.dev/${item.id}-grid-image.webp`} onError={e => {const img = e.currentTarget; if (!img.dataset.fallback) {img.dataset.fallback = "1"; img.src = asset(`items/${item.id}.webp`);} }} alt={item.name || item.shortName || "アイテム"} loading="lazy" decoding="async" /><span><strong>{item.nameJa || item.shortName || item.name}</strong><small>{item.name}</small></span></div>)}</div>}</div></div>;})}</section>
    {media.length > 0 && <section className="locationMedia"><div className="detailTitle"><small>VISUAL LANDMARKS</small><h3>建物・室内・目印の参考画像</h3><p>画像をクリックすると全体を拡大できます。画像は公開Wikiのタスクページから取得しています。</p></div><div>{media.map(image => <figure key={image.url} role="button" tabIndex={0} onClick={() => setLightbox(image)} onKeyDown={e => {if (e.key === "Enter" || e.key === " ") setLightbox(image);}}><img src={image.url} alt={image.caption} loading="lazy" decoding="async" /><figcaption>{image.caption}<span>クリックして拡大 ⛶</span></figcaption></figure>)}</div></section>}
    {lightbox && <div className="imageLightbox" role="dialog" aria-modal="true" aria-label="参考画像の拡大表示" onClick={() => setLightbox(null)}><button type="button" onClick={() => setLightbox(null)} aria-label="拡大表示を閉じる">×</button><div onClick={e => e.stopPropagation()}><img src={lightbox.url} alt={lightbox.caption} loading="eager" decoding="async" /><p>{lightbox.caption}</p></div><small>背景をクリック、または Esc キーで閉じます</small></div>}
    {mapView && <TaskMapModal view={mapView} media={media} mediaLoading={false} wiki={task.wiki} onClose={() => setMapView(null)} />}
  </article>;
});
function WeaponBuildGuide({builds, loading, verified, wiki}: {builds: any[]; loading: boolean; verified: boolean; wiki: string;}) {
  const labels: Record<string, string> = {Ergonomics: "エルゴノミクス", Recoil: "反動", VerticalRecoil: "垂直反動", HorizontalRecoil: "水平反動", Weight: "重量", Durability: "耐久値", MagazineCapacity: "マガジン装弾数", SightingRange: "照準距離", MuzzleVelocity: "初速", Accuracy: "精度"}, comparison = (method: string, value: number) => {const operators: Record<string, string> = {">=": "以上", "=>": "以上", "more": "以上", "<": "未満", "<=": "以下", "=<": "以下", "less": "以下", "=": "ちょうど"}; return `${Number(value).toLocaleString()} ${operators[method] || method || ""}`.trim();};
  if (loading) return <section className="weaponBuildGuide"><div className="weaponBuildLoading"><i></i><b>最新の改造条件を取得中…</b><span>ベース武器・必須パーツ・性能条件を確認しています</span></div></section>;
  if (!builds.length) return <section className="weaponBuildGuide"><header><small>WEAPON BUILD</small><h3>武器改造ガイド</h3></header><div className="weaponBuildUnavailable"><b>{verified ? "このタスクには取得できる改造条件がありません" : "改造条件を取得できませんでした"}</b><p>ネット接続後にページを開き直すか、下の攻略ページで現在の条件を確認してください。</p>{wiki && <a href={wiki} target="_blank" rel="noreferrer">最新の改造条件を確認 ↗</a>}</div></section>;
  return <section className="weaponBuildGuide"><header><small>WEAPON BUILD</small><h3>具体的な改造内容</h3><p>上から順に用意し、最後に性能値を確認してください。</p></header>{builds.map((build, index) => <article className="weaponBuildCard" key={build.id || index}><div className="weaponBase"><span>STEP 1　ベース武器</span>{build.item && <><img src={build.item.inspectImageLink || build.item.gridImageLink || `https://assets.tarkov.dev/${build.item.id}-grid-image.webp`} alt="" loading="lazy" decoding="async" /><div><strong>{build.item.name || build.item.shortName}</strong><small>{build.item.shortName}</small></div></>}</div><div className="weaponParts"><h4>STEP 2　取り付ける必須パーツ</h4>{build.parts?.length ? <div>{build.parts.map((part: any) => <article key={part.id}><img src={part.gridImageLink || `https://assets.tarkov.dev/${part.id}-grid-image.webp`} alt="" loading="lazy" decoding="async" /><span><b>{part.name || part.shortName}</b><small>{part.shortName}</small></span></article>)}</div> : <p>個別指定の必須パーツはありません。</p>}{build.categories?.length > 0 && <div className="weaponCategories"><b>種類指定</b>{build.categories.map((category: any) => <span key={category.id}>{category.name}</span>)}</div>}</div><div className="weaponStats"><h4>STEP 3　完成後の性能条件</h4>{build.attributes?.length ? <div>{build.attributes.map((attribute: any) => <span key={attribute.name}><small>{labels[attribute.name] || attribute.name}</small><strong>{comparison(attribute.requirement?.compareMethod, attribute.requirement?.value)}</strong></span>)}</div> : <p>数値条件はありません。必須パーツが装着されていることを確認してください。</p>}</div><footer><b>STEP 4</b><span>武器の耐久・折り畳み状態・弾薬やマガジンを含めて条件を再確認し、Mechanicへ納品します。</span></footer></article>)}</section>;
}
function TaskMapModal({view, media, mediaLoading, wiki, onClose}: {view: any, media: TaskMedia[], mediaLoading: boolean, wiki: string, onClose: () => void;}) {
  const sanitary = view.taskId === "59689ee586f7740d1570bbd5" && ["6a576ccec23300f0309ab511", "6a56800fc1311a6bb4cecf9b"].includes(view.objectiveId), normalize = (value: string) => String(value || "").toLowerCase().replace(/[^a-z0-9ぁ-んァ-ヶ一-龠]/g, ""), mapName = normalize(view.map.name || view.map.nameJa || view.map.slug || ""), words = String(view.description || "").toLowerCase().replace(/[^a-z0-9ぁ-んァ-ヶ一-龠 ]/g, " ").split(/\s+/).filter((word: string) => word.length >= 3), scored = media.map((item, index) => ({item, index, score: (normalize(item.caption).includes(mapName) ? 4 : 0) + (/map|地図|location|場所/i.test(item.caption) ? 3 : 0) + words.reduce((score: number, word: string) => score + (normalize(item.caption).includes(normalize(word)) ? 1 : 0), 0)})).sort((a, b) => b.score - a.score), sanitarySpecific = sanitary ? (media.find(item => /sanitary|gas.?analy|laboratory|med.?lab|window|room|stash/i.test(item.caption) && !/banner|icon/i.test(item.caption)) || media.find(item => !/map|地図|banner|icon|logo/i.test(item.caption))) : undefined, specific = sanitarySpecific || (!sanitary ? scored.find(candidate => candidate.score >= 4)?.item : undefined), mapUrl = mapImageFor(view.map), image = specific ? {...specific, specific: true} : {url: sanitary ? "" : mapUrl, caption: sanitary ? "" : `${view.map.name || view.map.nameJa} 全体マップ`, specific: false}, landmarks = (sanitary ? media : scored.filter(candidate => candidate.item.url !== image.url && candidate.score > 0).map(candidate => candidate.item)).filter(item => item.url !== image.url).slice(0, 6), bounds = mapBounds[view.map.id], position = view.zone?.position; let marker: null | {left: number; top: number;} = null;
  if (!image.specific && bounds && position) {const [[startX, startZ], [endX, endZ]] = bounds, left = (position.x - startX) / (endX - startX) * 100, top = (position.z - startZ) / (endZ - startZ) * 100; marker = {left: Math.max(1, Math.min(99, left)), top: Math.max(1, Math.min(99, top))};}
  return <div className="taskMapModal" role="dialog" aria-modal="true" aria-label={`${view.map.name}の目的地マップ`} onClick={onClose}><button className="taskMapClose" type="button" onClick={onClose}>×</button><section onClick={e => e.stopPropagation()}><header><div><small>QUEST LOCATION MAP</small><h2>{view.map.nameJa || view.map.name}</h2><p>{view.description}</p></div>{position && <div className="mapCoordinate"><span>目的地座標</span><b>X {position.x.toFixed(1)} / Z {position.z.toFixed(1)}</b></div>}</header><div className="taskMapBody">{sanitary && <section className="sanitaryRoute"><header><small>目的地を確認済み</small><h3>新研究室 2階・窓際</h3><p>医療テントではありません。オフィスからスカイブリッジを渡った反対側の新しい研究室へ向かいます。</p></header><ol><li><b>1</b><span>Factoryのオフィス棟へ向かう</span></li><li><b>2</b><span>オフィス側からスカイブリッジを渡る</span></li><li><b>3</b><span>橋の突き当たりにある研究室へ入る</span></li><li><b>4</b><span>2階の部屋にある窓際でガスアナライザーを設置</span></li></ol><strong>注意：夜Factoryでは設置判定が出ない報告があります。昼Factoryで実行してください。</strong></section>}<div className="taskMapGuideSteps"><span><b>01</b>全体マップで位置を確認</span><span><b>02</b>建物・入口の外観を確認</span><span><b>03</b>室内・対象物を確認</span></div>{mediaLoading ? <div className="taskMapLoading"><i></i><b>目的地画像を読み込み中…</b><span>タスク専用マップと建物・入口画像を確認しています</span></div> : <>{image.url ? <><div className="taskMapCanvas"><img src={image.url} alt={`${view.map.name}のタスク目的地マップ`} loading="eager" decoding="async" />{image.specific && <strong className="taskMapVerified">TASK-SPECIFIC MAP</strong>}{marker && <div className="questMapMarker" style={{left: `${marker.left}%`, top: `${marker.top}%`}}><i></i><b>目的地</b></div>}</div><p className="taskMapCaption">{image.caption}</p></> : <div className="taskMapUnavailable"><b>目的地画像を取得できませんでした</b><p>右下のタスク専用攻略ページから確認できます。</p></div>}{landmarks.length > 0 && <section className="taskLandmarks"><header><div><small>VISUAL ROUTE</small><h3>{sanitary ? "研究室・窓際のタスク専用画像" : "建物・入口・室内の参考画像"}</h3></div><span>{landmarks.length}枚</span></header><div>{landmarks.map((item, index) => <a href={item.url} target="_blank" rel="noreferrer" key={item.url}><i>{String(index + 1).padStart(2, "0")}</i><img src={item.url} alt={item.caption} loading="lazy" decoding="async" /><span>{item.caption}<small>クリックして原寸表示</small></span></a>)}</div></section>}</>}</div><footer>{mediaLoading ? <span>目的地画像を準備しています</span> : image.specific ? <span className="markerReady">● このタスク専用の目的地画像です</span> : marker ? <span className="markerReady">● 赤い印が目的地です</span> : sanitary ? <span className="markerReady">● 上の手順で新研究室2階へ向かってください</span> : <span>全体マップと下の参考画像を照合してください</span>}{wiki && <a href={wiki} target="_blank" rel="noreferrer">タスク専用攻略ページを確認 ↗</a>}</footer></section></div>;
}


