import fs from "node:fs";
import pngToIco from "png-to-ico";
import { rcedit } from "rcedit";
import sharp from "sharp";
const source="public/hideout/18.png",png="work/app-icon.png";
const ico="electron/icon.ico";
await sharp(source).resize(256,256,{fit:"contain",background:{r:14,g:16,b:14,alpha:1}}).png().toFile(png);
fs.writeFileSync(ico,await pngToIco(png));
const exe=process.argv[2]||"outputs/Tarkov-Stash-Ledger-App/Tarkov Stash Ledger.exe";
if(fs.existsSync(exe))await rcedit(exe,{icon:ico,"version-string":{ProductName:"Tarkov Stash Ledger",FileDescription:"Escape from Tarkov item and progression tracker"},"file-version":"1.0.0","product-version":"1.0.0"});
console.log("Windows icon generated and embedded.");
